version: "3"
services:
  app:
    image: pmprcoger/symfony:latest-dev
    volumes:
      - ./:/srv/app
    ports:
      - "443:443"
    environment:
      - APP_ENV=dev
    networks:
      webnet:
    links:
      - db_postgres
  db_postgres:
    build:
      dockerfile: Dockerfile
      context: ./docker/db_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=vagalumes
      - POSTGRES_USER=vagalumes
      - POSTGRES_DB=vagalumes
    networks:
      webnet:
networks:
  webnet:

